### ISSUE TITLE
Please support OpenSUSE 42.3 (Leap)

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#119]
I couldn't find 42.3 it in distributions.py. Please support the latest version of OpenSUSE Leap.

**Comment by dlasalle** [comment]
I'll try to get version 0.9.6 up into pypi later today, with this fix in it.

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Closing the defect as Leap 42.3 is in.
