### ISSUE TITLE
Please add support for CentOS 7.4

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#143]
Hi,

CentOS 7.4 has been released in Sep 2017. Please add it to the matrix.

**Comment by jarun** [comment]
Any plans to include this in the matrix?

**Comment by dlasalle** [comment]
I'll try and get to it this weekend.

At some point I'd like to add command line options for specifying custom images/distributions and/or some configuration file for extending the distributions.py file (maybe have it check the local directory for a .packagecore_distributions file or something). Let me know your thoughts on these approaches.
