### ISSUE TITLE
Ubuntu 18.04 build fails

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#146]
It seems the build times out while configuring tzdata.
Logs here: http://paste.ubuntu.com/p/ZznSVWmbBg/

**Comment by jarun** [comment]
It seems `python3-dateutil` needs tzdata which needs an interactive configuration. But this doesn't happen in Ubuntu 17.10 or 16.04.

**Comment by jarun** [comment]
For now I have commented out the `python3-dateutil` dep and build was successful. Leaving the issue open in case something can be done.

**Comment by dlasalle** [comment]
I'm gonna do some experimenting to see if doing:
```
DEBIAN_FRONTEND=noninteractive apt-get ...
```
fixes the issue for the debian-based OS's.

**Comment by jarun** [comment]
:+1:

**Comment by dlasalle** [comment]
Keeping this open until v0.9.11 is in PyPI.

**Comment by dlasalle** [comment]
Just uploaded `0.9.11` to PyPI.

**Comment by jarun** [comment]
Still fails. Logs here: http://paste.ubuntu.com/p/hHDrRnr23g/
