### ISSUE TITLE
export environment variables to docker containers

### ISSUE THREAD

**Issue by dilawar** [BytePackager/packagecore#176]
I am behind proxy. I can't figure out how I can setup `http_proxy`, `https_proxy` variables such that package managers `yum`, `apt` etc can download the dependencies.

What is the way around proxy?

**Comment by dlasalle** [comment]
Sorry for the delay in my response.

Would adding a section to the `.yaml` file for these variables and/or command line parameters like `-e SOME_ENV_VAR=some_value`, address this?

**Comment by dilawar** [comment]
My current setup is following. The pacakgecore file is [here](https://github.com/dilawar/moose-core/blob/packagecore/packagecore.yaml). Docker is running on Ubuntu18.04 and setup to use proxy as described [here](https://docs.docker.com/network/proxy/#configure-the-docker-client) (not using `-e HTTPS_PROXY` here).

Now when I run `packagecore 3.2.0`, docker pulls `archlinux/base` image (this means docker is using PROXY variables); but inside the container, I don't think `pacman` has access to proxy variables. 

I think, if packagecore detects that proxy variables are set in `env`, then export them to all containers so that package mangers can work. This is my current understanding. 

> Would adding a section to the .yaml file for these variables and/or command line parameters like -e SOME_ENV_VAR=some_value, address this?

If I write proxy variables in yml file, then it __may__ not work on github/travis where there is not proxy. Command line parameters seem like a good idea to me.

**Comment by dlasalle** [comment]
@dilawar I Just uploaded a new version with this implemented (0.11.3) to PyPI. Let me know if it solves this for you and I'll close this issue (or especially let me know if it does not).

**Comment by dilawar** [comment]
There are couple of minor issues such as `http_proxy` is being quoted twice and `http://` prefix is causing error. I'll send a PR shortly.

**Comment by dlasalle** [comment]
@dilawar Sorry about that, I had tested it with the quotes removed but forgot to commit it. Thanks for creating the PR. It has been merged as well as an update to the documentation. If `0.11.4` works for you, please let me know and I'll close the issue.

**Comment by dilawar** [comment]
Just tested it, worked great. Thanks a lot.
