### ISSUE TITLE
Add Centos7.7

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#182]
Please update the supported distros.

CentOS: 7.7 and 8.0 released (https://en.wikipedia.org/wiki/CentOS)

Fedora: 22 to 28 have reached EOL (https://fedoraproject.org/wiki/End_of_life)

Ubuntu: 14.04, 16.10, 17.04, 17.10 have reached EOL (https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions)

For Ubuntu, I think it's reasonable to support only LTS releases.

**Comment by dlasalle** [comment]
DockerHub doesn't have the new versions of CentOS up yet (https://hub.docker.com/_/centos). Putting on hold until they are added. There's open issues for this CentOS/sig-cloud-instance-images#150 and CentOS/sig-cloud-instance-images#151.

I'm also splitting the cleanup of old distribions into a separate issue (#183).

Thanks.

**Comment by jarun** [comment]
Sure thing!

**Comment by dlasalle** [comment]
Split #184 for Centos8. Renaming this issue for just Centos7.7.

The docker image 7.7 is still not up yet.

**Comment by dlasalle** [comment]
Just pushed v0.11.8 to pypi with this.

**Comment by jarun** [comment]
:+1:
