### ISSUE TITLE
openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#194]
Would it be possible to support openSUSE Tumbleweed?

**Comment by dlasalle** [comment]
It should be, similar in the way that arch linux is supported. It looks like an official docker image is maintained here https://hub.docker.com/r/opensuse/tumbleweed/tags

**Comment by jarun** [comment]
Thank you!

**Comment by dlasalle** [comment]
I want to get this cirlce-ci passing (#156) before I issue the new version, so it might be a day or two before this is up on pypi.

**Comment by jarun** [comment]
Do I need to specify any container?

For arch linux I do: `container: "archlinux/base"`

**Comment by dlasalle** [comment]
@jarun I just posted v0.11.10. 

You shouldn't need to specify a container for archlinux any more, as there is now an official image. However, recent versions of it are breaking (#201), so it currently uses an image from March, but should work for a while.
