### ISSUE TITLE
Installation requires the yaml-package

### ISSUE THREAD

**Issue by skx** [BytePackager/packagecore#22]
Upon a pristine (Debian stretch) system installation failed:

      root@docker:~/packagecore# ./setup.py install
      running install
      running bdist_egg
      running egg_info
      creating packagecore.egg-info
      writing packagecore.egg-info/PKG-INFO
      writing requirements to packagecore.egg-info/requires.tx
      ...
      ...
      Writing /tmp/easy_install-bxliko95/PyYAML-3.12/setup.cfg
      Running PyYAML-3.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bxliko95/PyYAML-3.12/egg-dist-tmp-2qxsqqu3build/temp.linux-x86_64-3.5/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
       #include <yaml.h>
                  ^

Installing  the yaml-dev package fixed it:

     apt-get install libyaml-dev

This should be noted in the travis-section of the documentation.

**Comment by dlasalle** [comment]
#25 Add documentation for Travis-CI, Circle-CI, add at the top of the readme talking about the pip installation.
