### ISSUE TITLE
Support Debian!

### ISSUE THREAD

**Issue by skx** [BytePackager/packagecore#24]
`packagecore/distributions.py` should be updated to include `debian:stretch` and `debian:jessie`.

PS.  Neat project idea.  Sorry for the bug-reports.

**Comment by dlasalle** [comment]
I really appreciate all of the feedback (so please keep the bug-reports/requests coming if you have more). Thanks.

**Comment by skx** [comment]
You're welcome.  I've got my package building on Ubuntu at the moment, tomorrow I'll try centos.

Other than the duplication in having to specify the dependencies twice, once before building, and once for the package meta-data, it seems pretty neat.

I'll report anything else that jumps out :)
