### ISSUE TITLE
Reruning a build fails if the output file hasn't changed.

### ISSUE THREAD

**Issue by skx** [BytePackager/packagecore#26]
With my sample, working, `packagecore.yaml` file in place I could build things as I expected:

     root@docker:~/lumail# packagecore -c packagecore.yaml 3.1

The second time I did it this failed right at the very last step:

       (Reading database ... 6513 files and directories currently installed.)
       Preparing to unpack .../lumail_3.1-1_amd64.deb ...
       Unpacking lumail (3.1-1) ...
       Setting up lumail (3.1-1) ...
       Cleaning up self packagecore-a95333cb6546b5d8.
       packagecore-a95333cb6546b5d8
       packagecore-a95333cb6546b5d8
       Failed to build package for 'ubuntu16.10'.
       Traceback (most recent call last):
         File "/usr/local/lib/python3.5/dist-packages/packagecore-0.7.2-py3.5.egg/packagecore/packager.py", line 187, in run
           shutil.move(tmpfile, self._outputDir)
         File "/usr/lib/python3.5/shutil.py", line 542, in move
    raise Error("Destination path '%s' already exists" % real_dst)
       shutil.Error: Destination path './lumail_3.1-1_amd64.deb' already exists

Removing the previously-generated `lumail_3.1-1_amd64.deb` file allowed the build to work.

> **NB** THis might have been my bug, perhaps I should have specified a different build-number.  i.e. "`packagecore -c packagecore.yaml 3.1 2`."

**Comment by dlasalle** [comment]
This is related to #17 , as over writing would be much more intuitive behaviour.

While in theory the build/release number should always be incremented for builds of the same version, I'm not aware of an easy way to do that in current CI systems.

**Comment by skx** [comment]
Yeah this is a duplicate, sorry.  I'll close.
